//! Guest webview types and bridge command names.
//!
//! Guests are secondary Chromium views hosted inside a single
//! [`crate`]-backed window. The app UI (primary webview) creates and
//! controls them via `fenestra.guest.*` bridge commands. Guest pages do
//! not receive the privileged bridge allow-list unless the host
//! explicitly opts in.

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::bridge::{BridgeCommand, BridgeError, BridgeResponse, BridgeResult};

pub const CREATE_COMMAND: &str = "fenestra.guest.create";
pub const DESTROY_COMMAND: &str = "fenestra.guest.destroy";
pub const NAVIGATE_COMMAND: &str = "fenestra.guest.navigate";
pub const SET_BOUNDS_COMMAND: &str = "fenestra.guest.setBounds";
pub const SET_VISIBLE_COMMAND: &str = "fenestra.guest.setVisible";
pub const SET_COVERED_COMMAND: &str = "fenestra.guest.setCovered";
pub const FOCUS_COMMAND: &str = "fenestra.guest.focus";
pub const RELOAD_COMMAND: &str = "fenestra.guest.reload";
pub const GO_BACK_COMMAND: &str = "fenestra.guest.goBack";
pub const GO_FORWARD_COMMAND: &str = "fenestra.guest.goForward";
pub const LIST_COMMAND: &str = "fenestra.guest.list";
pub const GET_COMMAND: &str = "fenestra.guest.get";
pub const SET_ZOOM_COMMAND: &str = "fenestra.guest.setZoom";
pub const EXECUTE_JS_COMMAND: &str = "fenestra.guest.executeJavaScript";
pub const DOWNLOAD_ACTION_COMMAND: &str = "fenestra.guest.downloadAction";

/// Reserved guest id used by the legacy `fenestra.popup` surface.
pub const POPUP_GUEST_ID: &str = "__fenestra_popup";

const INTERNAL_COMMANDS: [&str; 15] = [
    CREATE_COMMAND,
    DESTROY_COMMAND,
    NAVIGATE_COMMAND,
    SET_BOUNDS_COMMAND,
    SET_VISIBLE_COMMAND,
    SET_COVERED_COMMAND,
    FOCUS_COMMAND,
    RELOAD_COMMAND,
    GO_BACK_COMMAND,
    GO_FORWARD_COMMAND,
    LIST_COMMAND,
    GET_COMMAND,
    SET_ZOOM_COMMAND,
    EXECUTE_JS_COMMAND,
    DOWNLOAD_ACTION_COMMAND,
];

/// How a guest handles `window.open` / `target=_blank`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GuestPopupPolicy {
    /// Cancel the popup and emit `guest.newWindow` for the app to handle.
    #[default]
    Deny,
    /// Allow Chromium to open a native popup window.
    Allow,
    /// Open the URL inside the same guest (navigate in place).
    NavigateSame,
    /// Open the URL in a new guest webview with the same partition.
    OpenGuest,
}

impl GuestPopupPolicy {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "deny" | "block" => Some(Self::Deny),
            "allow" => Some(Self::Allow),
            "navigateSame" | "navigate_same" | "same" => Some(Self::NavigateSame),
            "openGuest" | "open_guest" | "guest" => Some(Self::OpenGuest),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Deny => "deny",
            Self::Allow => "allow",
            Self::NavigateSame => "navigateSame",
            Self::OpenGuest => "openGuest",
        }
    }
}

/// Pixel bounds of a guest relative to the host window client area.
///
/// Values are in **CSS pixels / DIPs** (what `getBoundingClientRect()`
/// returns). The WebView2 host converts them to physical pixels using the
/// window DPI before calling `SetWindowPos` / `SetBounds`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestBounds {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
}

impl GuestBounds {
    pub fn new(x: i32, y: i32, width: u32, height: u32) -> Self {
        Self {
            x,
            y,
            width: width.max(1),
            height: height.max(1),
        }
    }

    pub fn normalized(self) -> Self {
        Self {
            x: self.x,
            y: self.y,
            width: self.width.max(1),
            height: self.height.max(1),
        }
    }
}

/// Options for creating a guest webview.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestCreateOptions {
    /// Stable guest id. Generated by the host when omitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Initial URL. Mutually exclusive with `html` when both are empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Inline HTML document loaded as a data URI when `url` is absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(default)]
    pub bounds: GuestBounds,
    /// Cookie / cache partition key. Guests with the same partition share
    /// storage. Defaults to a private partition per guest id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub partition: Option<String>,
    /// When true, inject `window.fenestra` with the host allow-list.
    /// Defaults to false — guest pages are untrusted.
    #[serde(default)]
    pub allow_bridge: bool,
    #[serde(default = "default_true")]
    pub visible: bool,
    #[serde(default)]
    pub popup_policy: GuestPopupPolicy,
    /// When true, the guest may start downloads (emitted as events).
    #[serde(default = "default_true")]
    pub allow_downloads: bool,
    /// Optional background color as `#RRGGBB` or `#AARRGGBB`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
}

fn default_true() -> bool {
    true
}

impl Default for GuestCreateOptions {
    fn default() -> Self {
        Self {
            id: None,
            url: None,
            html: None,
            bounds: GuestBounds::new(0, 0, 1, 1),
            partition: None,
            allow_bridge: false,
            visible: true,
            popup_policy: GuestPopupPolicy::Deny,
            allow_downloads: true,
            background_color: None,
        }
    }
}

impl GuestCreateOptions {
    pub fn from_value(value: &Value) -> Result<Self, BridgeError> {
        let mut options: Self = if value.get("bounds").is_some() {
            serde_json::from_value(value.clone()).map_err(|error| {
                BridgeError::new(format!("invalid guest.create options: {error}"))
            })?
        } else {
            let mut without_bounds = value.clone();
            if let Some(object) = without_bounds.as_object_mut() {
                object.insert(
                    "bounds".to_string(),
                    json!({
                        "x": int_field(value, "x").unwrap_or(0),
                        "y": int_field(value, "y").unwrap_or(0),
                        "width": uint_field(value, "width").unwrap_or(1),
                        "height": uint_field(value, "height").unwrap_or(1),
                    }),
                );
            }
            serde_json::from_value(without_bounds).map_err(|error| {
                BridgeError::new(format!("invalid guest.create options: {error}"))
            })?
        };
        options.bounds = GuestBounds::new(
            int_field(value, "x").unwrap_or(options.bounds.x),
            int_field(value, "y").unwrap_or(options.bounds.y),
            uint_field(value, "width").unwrap_or(options.bounds.width),
            uint_field(value, "height").unwrap_or(options.bounds.height),
        )
        .normalized();
        if let Some(bounds) = value.get("bounds") {
            options.bounds = GuestBounds::new(
                int_field(bounds, "x").unwrap_or(options.bounds.x),
                int_field(bounds, "y").unwrap_or(options.bounds.y),
                uint_field(bounds, "width").unwrap_or(options.bounds.width),
                uint_field(bounds, "height").unwrap_or(options.bounds.height),
            )
            .normalized();
        }
        if options.url.as_deref().is_none_or(str::is_empty)
            && options.html.as_deref().is_none_or(str::is_empty)
        {
            return Err(BridgeError::new(
                "guest.create requires a non-empty `url` or `html`",
            ));
        }
        if let Some(id) = &options.id {
            let id = normalize_guest_id(id)?;
            options.id = Some(id);
        }
        if let Some(policy) = value
            .get("popupPolicy")
            .or_else(|| value.get("popup_policy"))
            .and_then(Value::as_str)
        {
            options.popup_policy = GuestPopupPolicy::parse(policy).ok_or_else(|| {
                BridgeError::new(format!("unknown guest popupPolicy: {policy}"))
            })?;
        }
        Ok(options)
    }
}

/// Snapshot of a live guest returned by `list` / `get` / `create`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestInfo {
    pub id: String,
    pub url: String,
    pub title: String,
    pub bounds: GuestBounds,
    pub visible: bool,
    pub loading: bool,
    pub can_go_back: bool,
    pub can_go_forward: bool,
    pub partition: String,
    pub allow_bridge: bool,
    pub popup_policy: GuestPopupPolicy,
    pub zoom_factor: f64,
}

impl GuestInfo {
    pub fn to_json(&self) -> Value {
        json!({
            "id": self.id,
            "url": self.url,
            "title": self.title,
            "bounds": {
                "x": self.bounds.x,
                "y": self.bounds.y,
                "width": self.bounds.width,
                "height": self.bounds.height,
            },
            "x": self.bounds.x,
            "y": self.bounds.y,
            "width": self.bounds.width,
            "height": self.bounds.height,
            "visible": self.visible,
            "loading": self.loading,
            "canGoBack": self.can_go_back,
            "canGoForward": self.can_go_forward,
            "partition": self.partition,
            "allowBridge": self.allow_bridge,
            "popupPolicy": self.popup_policy.as_str(),
            "zoomFactor": self.zoom_factor,
        })
    }
}

/// Download lifecycle event emitted to the primary webview.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestDownloadEvent {
    pub guest_id: String,
    pub download_id: String,
    pub url: String,
    pub filename: String,
    pub mime_type: String,
    pub total_bytes: i64,
    pub received_bytes: i64,
    pub state: GuestDownloadState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GuestDownloadState {
    Requested,
    Progress,
    Completed,
    Cancelled,
    Interrupted,
}

impl GuestDownloadState {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Requested => "requested",
            Self::Progress => "progress",
            Self::Completed => "completed",
            Self::Cancelled => "cancelled",
            Self::Interrupted => "interrupted",
        }
    }
}

impl GuestDownloadEvent {
    pub fn to_json(&self) -> Value {
        json!({
            "guestId": self.guest_id,
            "downloadId": self.download_id,
            "url": self.url,
            "filename": self.filename,
            "mimeType": self.mime_type,
            "totalBytes": self.total_bytes,
            "receivedBytes": self.received_bytes,
            "state": self.state.as_str(),
            "savePath": self.save_path,
            "error": self.error,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GuestDownloadAction {
    Accept,
    Cancel,
    Pause,
    Resume,
}

impl GuestDownloadAction {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "accept" | "allow" => Some(Self::Accept),
            "cancel" | "deny" | "reject" => Some(Self::Cancel),
            "pause" => Some(Self::Pause),
            "resume" => Some(Self::Resume),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Accept => "accept",
            Self::Cancel => "cancel",
            Self::Pause => "pause",
            Self::Resume => "resume",
        }
    }
}

/// Host-control payloads sent over `FENESTRA_HOST_CONTROL` for guests.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum GuestHostControl {
    Create(GuestCreateOptions),
    Destroy { id: String },
    Navigate { id: String, url: String },
    SetBounds { id: String, bounds: GuestBounds },
    SetVisible { id: String, visible: bool },
    Focus { id: String },
    Reload { id: String, ignore_cache: bool },
    GoBack { id: String },
    GoForward { id: String },
    SetZoom { id: String, factor: f64 },
    ExecuteJavaScript { id: String, code: String },
    DownloadAction {
        download_id: String,
        action: GuestDownloadAction,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        save_path: Option<String>,
    },
    List,
    Get { id: String },
}

impl GuestHostControl {
    pub fn command_name(&self) -> &'static str {
        match self {
            Self::Create(_) => "guest.create",
            Self::Destroy { .. } => "guest.destroy",
            Self::Navigate { .. } => "guest.navigate",
            Self::SetBounds { .. } => "guest.setBounds",
            Self::SetVisible { .. } => "guest.setVisible",
            Self::Focus { .. } => "guest.focus",
            Self::Reload { .. } => "guest.reload",
            Self::GoBack { .. } => "guest.goBack",
            Self::GoForward { .. } => "guest.goForward",
            Self::SetZoom { .. } => "guest.setZoom",
            Self::ExecuteJavaScript { .. } => "guest.executeJavaScript",
            Self::DownloadAction { .. } => "guest.downloadAction",
            Self::List => "guest.list",
            Self::Get { .. } => "guest.get",
        }
    }

    pub fn to_host_value(&self) -> Value {
        serde_json::to_value(self).unwrap_or(Value::Null)
    }

    pub fn from_bridge_command(command: &BridgeCommand) -> Result<Self, BridgeError> {
        match command.name.as_str() {
            CREATE_COMMAND => Ok(Self::Create(GuestCreateOptions::from_value(
                &command.params,
            )?)),
            DESTROY_COMMAND => Ok(Self::Destroy {
                id: required_id(&command.params)?,
            }),
            NAVIGATE_COMMAND => Ok(Self::Navigate {
                id: required_id(&command.params)?,
                url: required_string(&command.params, "url")?,
            }),
            SET_BOUNDS_COMMAND => Ok(Self::SetBounds {
                id: required_id(&command.params)?,
                bounds: bounds_from_value(&command.params)?,
            }),
            SET_VISIBLE_COMMAND => Ok(Self::SetVisible {
                id: required_id(&command.params)?,
                visible: bool_field(&command.params, "visible").unwrap_or(true),
            }),
            FOCUS_COMMAND => Ok(Self::Focus {
                id: required_id(&command.params)?,
            }),
            RELOAD_COMMAND => Ok(Self::Reload {
                id: required_id(&command.params)?,
                ignore_cache: bool_field(&command.params, "ignoreCache")
                    .or_else(|| bool_field(&command.params, "ignore_cache"))
                    .unwrap_or(false),
            }),
            GO_BACK_COMMAND => Ok(Self::GoBack {
                id: required_id(&command.params)?,
            }),
            GO_FORWARD_COMMAND => Ok(Self::GoForward {
                id: required_id(&command.params)?,
            }),
            SET_ZOOM_COMMAND => Ok(Self::SetZoom {
                id: required_id(&command.params)?,
                factor: command
                    .params
                    .get("factor")
                    .and_then(Value::as_f64)
                    .unwrap_or(1.0)
                    .clamp(0.25, 5.0),
            }),
            EXECUTE_JS_COMMAND => Ok(Self::ExecuteJavaScript {
                id: required_id(&command.params)?,
                code: required_string(&command.params, "code")?,
            }),
            DOWNLOAD_ACTION_COMMAND => {
                let action_name = required_string(&command.params, "action")?;
                let action = GuestDownloadAction::parse(&action_name).ok_or_else(|| {
                    BridgeError::new(format!("unknown download action: {action_name}"))
                })?;
                Ok(Self::DownloadAction {
                    download_id: required_string(&command.params, "downloadId")
                        .or_else(|_| required_string(&command.params, "download_id"))?,
                    action,
                    save_path: command
                        .params
                        .get("savePath")
                        .or_else(|| command.params.get("save_path"))
                        .and_then(Value::as_str)
                        .map(str::to_string),
                })
            }
            LIST_COMMAND => Ok(Self::List),
            GET_COMMAND => Ok(Self::Get {
                id: required_id(&command.params)?,
            }),
            _ => Err(BridgeError::new(format!(
                "not a guest bridge command: {}",
                command.name
            ))),
        }
    }
}

/// Append guest bridge commands to an allow-list.
pub fn bridge_commands_with_guest(mut commands: Vec<String>) -> Vec<String> {
    for command in INTERNAL_COMMANDS {
        if !commands.iter().any(|existing| existing == command) {
            commands.push(command.to_string());
        }
    }
    commands
}

pub fn is_guest_command(name: &str) -> bool {
    INTERNAL_COMMANDS.contains(&name)
}

pub fn normalize_guest_id(id: &str) -> Result<String, BridgeError> {
    let trimmed = id.trim();
    if trimmed.is_empty() {
        return Err(BridgeError::new("guest id must not be empty"));
    }
    if trimmed.len() > 128 {
        return Err(BridgeError::new("guest id must be at most 128 characters"));
    }
    if !trimmed
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
    {
        return Err(BridgeError::new(
            "guest id may only contain ASCII alphanumerics, '-', '_', and '.'",
        ));
    }
    Ok(trimmed.to_string())
}

pub fn default_partition_for(id: &str) -> String {
    format!("guest:{id}")
}

pub fn ok_info(info: GuestInfo) -> BridgeResult {
    Ok(BridgeResponse::json(info.to_json()))
}

pub fn ok_list(guests: &[GuestInfo]) -> BridgeResult {
    Ok(BridgeResponse::json(json!({
        "guests": guests.iter().map(GuestInfo::to_json).collect::<Vec<_>>(),
    })))
}

pub fn ok_empty() -> BridgeResult {
    Ok(BridgeResponse::json(json!({})))
}

fn required_id(params: &Value) -> Result<String, BridgeError> {
    normalize_guest_id(&required_string(params, "id")?)
}

fn required_string(params: &Value, key: &str) -> Result<String, BridgeError> {
    params
        .get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
        .ok_or_else(|| BridgeError::new(format!("guest command requires a non-empty `{key}`")))
}

fn bounds_from_value(value: &Value) -> Result<GuestBounds, BridgeError> {
    if let Some(bounds) = value.get("bounds") {
        return Ok(GuestBounds::new(
            int_field(bounds, "x").unwrap_or(0),
            int_field(bounds, "y").unwrap_or(0),
            uint_field(bounds, "width").unwrap_or(1),
            uint_field(bounds, "height").unwrap_or(1),
        )
        .normalized());
    }
    Ok(GuestBounds::new(
        int_field(value, "x").unwrap_or(0),
        int_field(value, "y").unwrap_or(0),
        uint_field(value, "width").unwrap_or(1),
        uint_field(value, "height").unwrap_or(1),
    )
    .normalized())
}

fn int_field(value: &Value, key: &str) -> Option<i32> {
    value.get(key).and_then(|item| {
        item.as_i64()
            .map(|n| n as i32)
            .or_else(|| item.as_f64().map(|n| n as i32))
    })
}

fn uint_field(value: &Value, key: &str) -> Option<u32> {
    value.get(key).and_then(|item| {
        item.as_u64()
            .map(|n| n as u32)
            .or_else(|| item.as_f64().map(|n| n.max(0.0) as u32))
            .or_else(|| item.as_i64().map(|n| n.max(0) as u32))
    })
}

fn bool_field(value: &Value, key: &str) -> Option<bool> {
    value.get(key).and_then(Value::as_bool)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn create_options_require_url_or_html() {
        let error = GuestCreateOptions::from_value(&json!({
            "x": 10, "y": 20, "width": 800, "height": 600
        }))
        .unwrap_err();
        assert!(error.to_string().contains("url"));
    }

    #[test]
    fn create_options_parse_flat_bounds() {
        let options = GuestCreateOptions::from_value(&json!({
            "id": "browser-1",
            "url": "https://example.com",
            "x": 10,
            "y": 20,
            "width": 800,
            "height": 600,
            "popupPolicy": "deny",
        }))
        .unwrap();
        assert_eq!(options.id.as_deref(), Some("browser-1"));
        assert_eq!(options.bounds, GuestBounds::new(10, 20, 800, 600));
        assert_eq!(options.popup_policy, GuestPopupPolicy::Deny);
    }

    #[test]
    fn guest_commands_are_appended() {
        let commands = bridge_commands_with_guest(vec!["notes.list".into()]);
        assert!(commands.iter().any(|c| c == CREATE_COMMAND));
        assert!(commands.iter().any(|c| c == "notes.list"));
    }

    #[test]
    fn host_control_round_trips_create() {
        let command = BridgeCommand {
            name: CREATE_COMMAND.into(),
            params: json!({
                "url": "https://example.com",
                "x": 0,
                "y": 40,
                "width": 1200,
                "height": 800,
            }),
            origin: None,
        };
        let control = GuestHostControl::from_bridge_command(&command).unwrap();
        assert_eq!(control.command_name(), "guest.create");
    }
}
